default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: vagrant
  password: vagrant
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: library

test:
  <<: *default
  database: library

production:
  <<: *default
  database: library